/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/HelloWorld copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeButton: typeof import('./components/button/HomeButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserItem: typeof import('./components/UserItem.vue')['default']
  }
}
